function [obj, grad] = generatedObjective(inputVariables, extraParams)
%generatedObjective Compute objective function value and gradient
%
%   OBJ = generatedObjective(INPUTVARIABLES, EXTRAPARAMS) computes the
%   objective value OBJ at the point INPUTVARIABLES, using the extra
%   parameters in EXTRAPARAMS.
%
%   [OBJ, GRAD] = generatedObjective(INPUTVARIABLES, EXTRAPARAMS)
%   additionally computes the objective gradient value GRAD at the current
%   point.
%
%   Auto-generated by prob2struct on 18-May-2024 10:53:24

%% Compute objective function.
H = extraParams{1};
x = inputVariables(:);
f = extraParams{2}(:);

Hx = H*x;
obj = 0.5*dot(x, Hx) + dot(f, x);

if nargout > 1
    %% Compute objective gradient.
    % To call the gradient code, notify the solver by setting the
    % SpecifyObjectiveGradient option to true.
    grad = Hx + f;
end
end